// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-paintings.ts
import { createClient } from "npm:@supabase/supabase-js@^2.101.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function sb() {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_paintings_default = defineTool({
  name: "list_paintings",
  title: "List paintings",
  description: "List paintings from the Sali Arts gallery. Filter by availability (sold or available) or category.",
  inputSchema: {
    status: z.enum(["all", "available", "sold"]).default("all").describe("Filter paintings by sale status."),
    category: z.string().optional().describe("Optional category filter."),
    limit: z.number().int().min(1).max(100).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, category, limit }) => {
    let q = sb().from("paintings").select("id,title,price,category,medium,dimensions,year,sold,image_url,description").eq("active", true).limit(limit);
    if (status === "available") q = q.eq("sold", false);
    if (status === "sold") q = q.eq("sold", true);
    if (category) q = q.eq("category", category);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { paintings: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-painting.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.101.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_painting_default = defineTool2({
  name: "get_painting",
  title: "Get painting",
  description: "Get full details for a single painting by its ID.",
  inputSchema: { id: z2.string().uuid().describe("Painting UUID.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }) => {
    const sb2 = createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await sb2.from("paintings").select("*").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Painting not found." }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { painting: data } };
  }
});

// src/lib/mcp/tools/list-upcoming.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.101.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_upcoming_default = defineTool3({
  name: "list_upcoming_projects",
  title: "List upcoming projects",
  description: "List upcoming/in-progress art projects at Sali Arts.",
  inputSchema: { limit: z3.number().int().min(1).max(50).default(20) },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const sb2 = createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await sb2.from("upcoming_projects").select("*").limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { projects: data ?? [] } };
  }
});

// src/lib/mcp/tools/get-about.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.101.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_about_default = defineTool4({
  name: "get_about_info",
  title: "Get about info",
  description: "Get About and Contact information for the Sali Arts gallery (artist bio, contact details, site copy).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const sb2 = createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await sb2.from("site_content").select("section,key,value,image_url");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { content: data ?? [] } };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "sali-arts-mcp",
  title: "Sali Arts",
  version: "0.1.0",
  instructions: "Tools for browsing the Sali Arts online gallery: list paintings (available or sold), get painting details, list upcoming projects, and read About/Contact info.",
  tools: [list_paintings_default, get_painting_default, list_upcoming_default, get_about_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
